iad_training:
    resource: "@IadTrainingBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "Iad\Bundle\TrainingBundle\Business\BusinessTrainingService"
    type:     annotation

iad_training_test_service:
    path: /Business/BusinessTrainingService